# Custom Site Variables
site_title : Matthew Staton | Software Developer
navbar_title : Matthew Staton
landing_title: Matthew Staton
landing_tagline: Full Stack Developer with an interest in Mobile and IoT.