# Custom Site Variables
site_title: Matthew Staton | Software Developer
landing_title: I'm Matthew Staton
landing_tagline: Full Stack Developer with an interest in Mobile and IoT.

# Maintenance/updates
update_text: Update on projects and site coming soon.

# Other info
fullname: Matthew Staton
firstname: Matthew
lastname: Staton